spring.application.name=BBTTResort

# ================= SERVER =================
server.port=4040

# ================= MYSQL =================
spring.datasource.url=jdbc:mysql://localhost:3306/bbtt_resort_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Jackson ? dates d?ng ISO string thay vï¿½ timestamp array
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# ================= FILE =================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ================= CLOUDINARY =================
cloudinary.cloud-name=bbtt-resort
cloudinary.api-key=237175291189391
cloudinary.api-secret=8FQppchaa9V9siq-Iwj83vrerks

# ================= MAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=giabao27v@gmail.com
spring.mail.password=anywwxvmyzvsqocq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=8000
spring.mail.properties.mail.smtp.timeout=8000
spring.mail.properties.mail.smtp.writetimeout=8000

# ================= VNPAY =================
# VNPay Config
vnpay.tmnCode=1C4BTBYS
vnpay.secretKey=O9S2K8IPAM0N4V8H60BFSEVZY1N044HG
vnpay.returnUrl=http://localhost:3000/vnpay-return
vnpay.vnpayUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
